### ISSUE TITLE
does not compile on latest unity

### ISSUE THREAD

**Issue by tzurs** [MarekKowalski/LiveScan3D-Hololens#1]

**Comment by MarekKowalski** [comment]
Could you provide some more details please?

**Comment by LanceMcCarthy** [comment]
@MarekKowalski Someone else reported it with more info here: https://github.com/MarekKowalski/LiveScan3D-Hololens/issues/3

**Comment by MarekKowalski** [comment]
Closing this one since I assume it's connected either with issue #2 or issue #3 . If it is not please reopen.
