### ISSUE TITLE
Shader Error

### ISSUE THREAD

**Issue by bethhol** [MarekKowalski/LiveScan3D-Hololens#2]
Using Unity 5.6.0 There is a "shader error in 'Custom/GS Billboard' : 'UnityObjectToClipPos': cannot implicitly convert from 'float4x4' to 'float4' at line 82 ( on d3d11)"

**Comment by MarekKowalski** [comment]
Thanks for letting me know, I'll install Unity 5.6.0 and take a look.

**Comment by MarekKowalski** [comment]
Turns out Unity 5.6.0 automatically modified the shader which caused the error. It should work now.
