### ISSUE TITLE
Building and Deploying the LiveScan3D-Hololens (Windows 10 and Unity)

### ISSUE THREAD

**Issue by sarkrishnan** [MarekKowalski/LiveScan3D-Hololens#21]
@MarekKowalski I have tried to open the LiveScan3D-Hololens with different versions of Unity.

Unity 5.6.1f1 crashes when I open the the project. Same result with Unity 5.6.0 too. I have tried auto-port (offered by Unity in latest version unity 2019.x and 2018.x) and there are complilation issues. In summary, I have livescan3D working properly but struggling to get LiveScan3D-Hololens to work with windows 10 and different versions of Unity. 

Can you please say which windows version you used originally or the combined version of windows and unity (5.6.0 or Unity 5.6.1f1,...) that worked for you? I tried in Windows 10 Enterprise 64-bit (10.0, Build 17763).

Thank you and cheers,
Aravinda

P.S: A shout out to @marc-hanheide (my mentor) since he wished to join the discussion.

**Comment by MarekKowalski** [comment]
Hmm, that's a weird one. There is no error from Unity, right? Does it crash immediatelly when you open the directory? Have you tried removing some of the files and then opening? What compilation errors do you get?

I'm not sure which Unity version I was using for this in the past. 

Marek

**Comment by MarekKowalski** [comment]
Looks like someone got the project to open in 5.6.0f3 recently: https://github.com/MarekKowalski/LiveScan3D-Hololens/issues/22

**Comment by sarkrishnan** [comment]
Thanks @MarekKowalski I have reached out to the issue opener in #22

**Comment by sarkrishnan** [comment]
Hi @MarekKowalski 

I am able to successfully deploy the app in Windows 10. I am giving the details of the version I used for everyone's reference.

Unity - 2018.4.14f1
Visual Studio - Microsoft Visual Studio Community 2019 Version 16.4.2 

Cheers,
Aravinda 

P.S: I am closing this issue since I was able to build and deploy in Windows 10

**Comment by sarkrishnan** [comment]
Hi @MarekKowalski 

I am able to successfully deploy the app in Windows 10. I am giving the details of the version I used for everyone's reference.

Unity - 2018.4.14f1
Visual Studio - Microsoft Visual Studio Community 2019 Version 16.4.2 

Cheers,
Aravinda 

P.S: I am closing this issue since I was able to build and deploy in Windows 10
