### ISSUE TITLE
Hololens2 issue with MRTK Version

### ISSUE THREAD

**Issue by GitMaxOch** [MarekKowalski/LiveScan3D-Hololens#35]
Hey,
I tried to get the new version for the Hololens 2 running but i get some issues. 
If i am use the version of MRTK that comes in the folder it doesnt show the point cloud 
and i tried to update the version of mrtk but this doesnt work at all.

can you help me with my Promblem?

Best regards 
Max

**Comment by MarekKowalski** [comment]
Hello Max,

unfortunately I don't really have the bandwidth to try this at the moment. Does this work for you locally (as in, not on HL2)?
Do you get any exception on HL2? Is the HL2 on the same network as the machine? Do you have the firewall set up such that the connection could happen?

Thanks,

Marek

**Comment by GitMaxOch** [comment]
Hey Marek,

Thanks for youre answer, i got it working in Unity (Version 2020.1.17) but if i try deploing it remote using Visual studio 19 to the holonens2 i get this error
![Screenshot 2024-05-10 153033](https://github.com/MarekKowalski/LiveScan3D-Hololens/assets/152156585/05dc9fd0-da9f-40f7-8441-4781a5b292e8)
First the HL2 shows "made with unity" and then the error occurs in VS19. 

What Firewall setup do you mean? 

Thanks,
Max

**Comment by MarekKowalski** [comment]
That's not very specific. Does it come with a stack trace? I wonder if it has anything to do with the networkcommunication module. Are you able to set a breakpoint where that module is initialized and see whether it fails there?

For the firewall: the hololens2 needs to be able to connect to the livescan app running on your pc.

**Comment by GitMaxOch** [comment]
Hey Marek,

this is in the stack

![grafik](https://github.com/MarekKowalski/LiveScan3D-Hololens/assets/152156585/d09fb89e-62f8-4cb8-84da-2c7d5e030e69)

i´m not very into programming using Unity. Where is network module getting initialized. 

I checkt the settings of the firewall and the livescanapp has access.

Thanks,
Max

**Comment by MarekKowalski** [comment]
Hey!

It seems that the failure happens during construction of the socket. Based on the stack trace, it's hard to determine whether this is a failure in the constructor itself or whether the constructor does not even start.

A few things you could try:
1. Rebuild the Network Communications project. Make sure that the output DLL is saved in ./Assets/Plugins.
2. Remove the following line `socket = SocketClient(strIP, port); ` from the TransferSocket.cpp file, rebuild (as in step 1 above) and see if you get the exact same error and stack trace. If it's the same then there is some issue with the DLL I would think. If not, then it looks like a network issue, i.e. your HL2 can't connect to the computer.

**Comment by GitMaxOch** [comment]
Hey, 
Thanks for you`re support. 
I tried youre suggestions and with rebuilding the networkcommunication it did made a difference, the same error appeared. 

When commenting out the line, the program ran without making an error.
So I got the following result.
![Screenshot 2024-05-22 124032](https://github.com/MarekKowalski/LiveScan3D-Hololens/assets/152156585/408b85e8-1bbb-49ca-a022-244a79593be9)

You said if this happens it should be a network issue so I tried turning off my firewall but the same error accured again.

Best regards
Max

**Comment by MarekKowalski** [comment]
Hello Max,

at this point it's hard for me to help you without knowing your network setup. Are you certain that the network allows communciation on port 48002? When you open the app on hololens you should get a keyboard input asking for an IP. Are you sure you are using the right IP address for your computer?

One way to test the network outside of a HoloLens would be to take the following steps:
1. Run the server/player on the same machine you usually do.
2. Set up the Unity project on another computer connected to the same wifi as the Hl2.
3. Modify line 21 here: https://github.com/MarekKowalski/LiveScan3D-Hololens/blob/d93cb12d80567c6b1e065d1da005feffc3aaa05a/HololensReceiver/Assets/KeyboardInput.cs#L21 to be the IP address of the machine where you are running the server/player.
4. Run the Unity project and see if it receives the data. 

Marek

**Comment by GitMaxOch** [comment]
Hey Marek,

i got it finally working, i hardcoded the ip adress also into this line 
https://github.com/MarekKowalski/LiveScan3D-Hololens/blob/d93cb12d80567c6b1e065d1da005feffc3aaa05a/HololensReceiver/Assets/KeyboardInput.cs#L31
and in the pointcloud reciver where the ip adress is refered.

I also run the livescanserver on a different pc, maybe this was the solution for our network problems

Do you know how i get rid of the white polygons in the background.

![Screenshot 2024-05-27 155350](https://github.com/MarekKowalski/LiveScan3D-Hololens/assets/152156585/58d2e77b-06e8-479e-85f3-bd5772dd2411)
 
Thank you so much for your help so far.

Best regards
Max

**Comment by MarekKowalski** [comment]
I am glad it's working for you! The black mesh you are seeing is the 3D reconstrurction of the scene from the HoloLens. At the moment I  do not remember how to switch it off. Please look at the HL2/MRTK documentation.
