### ISSUE TITLE
Application exits when runs on hololens but works perfectly in Unity Editor

### ISSUE THREAD

**Issue by krishnabhaskar** [MarekKowalski/LiveScan3D-Hololens#8]
Hi,
When application is deployed to Microsoft Hololens, app opens asking to enter IP address. When server IP address is entered and submitted, it exits the application within few seconds. But in unity editor point cloud is rendered perfectly.
Unity Version - 5.6.0
Visual Studio Version - Visual Studio Community 2015.
LiveScan3d SDK - Livescan3d-1.0.0-vc12
Build Type - XAML UWP
Could you please have a look into this issue.
Thanks

**Comment by MarekKowalski** [comment]
Hi! Can you access the HoloLens device protal from the server machine? Also, have you checked the firewall settings?

Thanks,
Marek

**Comment by krishnabhaskar** [comment]
Now it works. Thanks a lot !!!

**Comment by krishnabhaskar** [comment]
Hi,
Can this sdk work with Kinect v1 ???
If no, can u please tell how any possibility with the source code to make it work with Kinect v1.

Thanks
Krishna

**Comment by NYhale** [comment]
> 现在它起作用了。多谢！！！

I also encountered this problem, how did you solve it? thank you
